version: '3.8' 
services: # apps containers you want to build and run
  madhuriapp1: # name of appliction for compose 
    image: madhuridotnetimg:v1  # image i want to build 
    build: .  # path of dockerfile location -- . means current 
    container_name: madhuric1 # it will create container also 
  madhuriapp2: 
    image: madhurihttpd:v1 
    build: 
      context: . #location of dockerfile 
      dockerfile: httpd.dockerfile # name of dockerfile 
    container_name: madhuric2 
    ports:
      - 2027:80  
  
